server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: sp-security
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/time_line?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
      host: 188.131.221.99
      port: 6379
      timeout: 30s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

token:
  expire:
    seconds: 7200
  jwtSecret: (ZHENG:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

es:
  host: 188.131.221.99
  port: 9200
  scheme: http






#elasticsearch配置
elastic-search:
  hostName: 188.131.221.99
  port: 9200






